<?php

namespace AppBundle\Repository;

/**
 * BoughtProductsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BoughtProductsRepository extends \Doctrine\ORM\EntityRepository
{
}
